services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Default for prod builds
    ports:
      - "3000:3000"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001