FROM ruby:3.4.1-slim

WORKDIR /txms

# Install dependencies needed for Ruby gems compilation and Rails
RUN apt-get update -qq && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libyaml-dev \
    pkg-config \
    curl \
    libjemalloc2 \
    libvips \
    sqlite3 \
    nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

COPY . .

# Add entrypoint script
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["entrypoint.sh"]
CMD ["rails", "server", "-b", "0.0.0.0"]
